# Generated by Django 5.2.7 on 2025-10-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ror_id', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_uc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('journal_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=50)),
                ('issue_number', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edboards.journal')),
            ],
            options={
                'unique_together': {('journal', 'issue_number', 'volume')},
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Editor-in-Chief', 'Editor-in-Chief'), ('Associate Editor', 'Associate Editor'), ('Editorial Board Member', 'Editorial Board Member'), ('Guest Editor', 'Guest Editor')], default='Editorial Board Member', max_length=255)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edboards.institution')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edboards.issue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edboards.person')),
            ],
        ),
    ]
