# Generated by Django 5.2.7 on 2026-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboardmember',
            name='other_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='source_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('Static Page', 'Static Page'), ('Missing', 'Missing'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='has_janeway_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editorialboardmember',
            name='role',
            field=models.CharField(choices=[('Executive Editor', 'Executive Editor'), ('Editor-in-Chief', 'Editor-in-Chief'), ('Co-Editor-in-Chief', 'Co-Editor-in-Chief'), ('Senior Editor', 'Senior Editor'), ('Associate Editor', 'Associate Editor'), ('Managing Editor', 'Managing Editor'), ('Handling Editor', 'Handling Editor'), ('Section Editor', 'Section Editor'), ('Review Editor', 'Review Editor'), ('Editorial Assistant', 'Editorial Assistant'), ('Editor', 'Editor'), ('Editorial Board Member', 'Editorial Board Member'), ('Advisory Board Member', 'Advisory Board Member'), ('Advisory Editor', 'Advisory Editor'), ('Honorary Editor', 'Honorary Editor'), ('Designer / Production Editor', 'Designer / Production Editor'), ('Writer', 'Writer'), ('Copyeditor', 'Copyeditor'), ('Publicity Editor', 'Publicity Editor'), ('Advisor', 'Advisor'), ('Other', 'Other')], default='Editorial Board Member', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ror_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
