# Generated by Django 5.2.7 on 2026-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edboards', '0002_editorialboardmember_other_role_issue_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
