# Generated by Django 5.2.8 on 2026-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edboards', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='ror_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
